Drop dependancy for some testing because cfbs bs
lib-sshd-config is not yet in the main index, so i added by repo:

[root@hub cfbs]# cfbs add https://github.com/nickanderson/cfengine-ssh
Found 2 modules in 'https://github.com/nickanderson/cfengine-ssh':
  - inventory-ssh-host-key-fingerprints
  - lib-sshd-config
Do you want to add all 2 of them? [y/N] y
Added module: inventory-ssh-host-key-fingerprints
Added module: lib-sshd-config

But, I cant add a module that depends on lib-sshd-config because it
errors (likely since it's not in the main index), even though it is listed in
the cfbs.json in my project root.

[root@hub cfbs]# cfbs add https://github.com/nickanderson/cfengine-security-hardening
Found 7 modules in 'https://github.com/nickanderson/cfengine-security-hardening':
  - default-encrypt-method-sha512
  - sshd-PermitRootLogin-no
  - sshd-PermitEmptyPasswords-no
  - sshd-Ciphers-strong
  - sshd-X11Forwarding-no
  - sshd-MaxAuthTries
  - sshd-Protocol-2
Do you want to add all 7 of them? [y/N] y
Added module: default-encrypt-method-sha512
Error: Module 'lib-sshd-config' not found